### ISSUE TITLE
The installation from "Quick Start" does not work

### ISSUE THREAD

**Issue by CMon** [gammazero/nexus#120]
if I run:
`go get github.com/gammazero/nexus`

i get the following error:
`can't load package: package github.com/gammazero/nexus: no Go files in /home/<user>/go/src/github.com/gammazero/nexus`

so I guess it should be something like:
`go get github.com/gammazero/nexus/nexusd`
in the docs?

if I try the line with the nexusd then afterwards there is no nexusd folder to switch to so the whole Quick start does not work for me, what is the proper way to have a quick start with the nexus router (I guess cloning and so on, but it would be helpful to have a working Quick start or no Quick Start section in the docs)

go version go1.10.3 linux/amd64

**Comment by gammazero** [comment]
That needs to be `go get github.com/gammazero/nexus/...`  Will fix now.

**Comment by gammazero** [comment]
Thank you for raising this issue.  If you run into any other problems getting things started/running/configured, let me know and I will be happy to help.  If this and any related issues are fixed, please close this.

**Comment by gammazero** [comment]
Wow, did not realize how much has changed since the readme was last edited.  I will go through and update the whole thing as soon as I have a moment.  Thanks again.

**Comment by goldcode88** [comment]
"go get github.com/gammazero/nexus/..." didn't work in OSX. Nothing to be got. 
1.OSX 10.12.6
2.go version go1.10.1 darwin/amd64

**Comment by bevand10** [comment]
Perhaps a new issue?

Executed 5 mins ago...

```
$ go get -v github.com/gammazero/nexus/...
github.com/gammazero/nexus/transport
# github.com/gammazero/nexus/transport
go/src/github.com/gammazero/nexus/transport/websocketpeer.go:139:23: dialer.DialContext undefined (type websocket.Dialer has no field or method DialContext)
```

**Comment by gammazero** [comment]
@bevand10 I think that Gorilla needs freshening:
`go get -u github.com/gorilla/websocket`
