### ISSUE TITLE
RPC-progression blocked in router

### ISSUE THREAD

**Issue by HollowTooth** [gammazero/nexus#128]
Hello again :)

I've been testing progress RPC in nexus, and came across a bit of a problem.
I wrote up an example code:

```
package main

import (
	"github.com/gammazero/nexus/client"
	"github.com/gammazero/nexus/router"
	"fmt"
	"context"
	"github.com/gammazero/nexus/wamp"
)

func main() {
	r, _ := router.NewRouter(&router.Config{
		RealmConfigs: []*router.RealmConfig{
			{
				URI: "test",
				AnonymousAuth: true,
			},
		},
	}, nil)
	go router.NewWebsocketServer(r).ListenAndServe("localhost:8000")
	c, err := client.ConnectNet("ws://localhost:8000/", client.Config{
		Realm: "test",
	})
	if err != nil {
		fmt.Println("error", err)
	} else {
		c.Register("echo", func(context context.Context, args wamp.List, kwargs wamp.Dict, details wamp.Dict) (result *client.InvokeResult) {
			for range make([]interface{}, 1000) {
				err := c.SendProgress(context, args, kwargs)
				if err != nil {
					return &client.InvokeResult{
						Err: wamp.URI(err.Error()),
					}
				}
			}
			return &client.InvokeResult{
				Args: args,
				Kwargs: kwargs,
			}
		}, wamp.Dict{})
		x, err := client.ConnectNet("ws://localhost:8000/", client.Config{
			Realm: "test",
		})
		if err != nil {
			fmt.Println("error on x", err)
		} else {
			x.CallProgress(context.Background(), "echo", wamp.Dict{}, []interface{}{"test", 123}, nil, wamp.CancelModeKill, func(result *wamp.Result) {
				fmt.Println(result.Arguments)
			})
		}
	}
}
```

This code will block indefinitely, if the clients are not ran where the router is. Out of 10 tries, on a local machine, it only blocked twice in my case. Progress is being sent to fast, and the router sometime blocks requests. If that happens, `x.CallProgress` might never return, but it's not a deadlock (I waited for half an hour, so I assume, that it would never return).

Considering the last issue I posted here #105, I'm guessing the problem is similar, although it is for progress RPC calls and not a PubSub handler.

I can understand, the router blocking some of my RPC progress (although, I originally thought, that a confirmation message would be sent from the router to the callee), however the issue of the caller not returning from `x.CallProgress` is problematic.

I will try to get more debugging information on this.

**Comment by HollowTooth** [comment]
Hello again.

I have managed to figure out, where my issue was. The callee was a local database client, that sent every x amount of rows through progress. The caller was a nexus node, that lives in another country. Even if the progress that I receive on the caller is sent to a different goroutine (or makes a new goroutine to handle it), the data transfer is still too slow. 

The problem with `x.CallProgress` was, that my `cancel string` is `wamp.CancelModeKill` and not `wamp.CancelModeKillNoWait`, and since the last result (not progress), was also blocked, the caller waited to receive the message indefinitely.

**Comment by gammazero** [comment]
I am happy to hear you figured out the issue.  If there is any way I could make things easier, to use or to diagnose problems, I will consider any suggestions. Feature requests are always welcome, just open an [issue](https://github.com/gammazero/nexus/issues).

**Comment by HollowTooth** [comment]
Well, I am looking into the WAMP spec, if there is any mentioning of the caller (or the router) returning a ProgressRecieved message or anything like that, but no luck so far. 
Without the callee knowing, if the message went through, there is no elegant way to fix this.
I was thinking, of having a pubsub channel, dedicated to this one RPC call, rothe caller sends a received message to the callee.

In case, that the wamp spec does not mention any sort of message, then I see no reason to keep this issue open. I don't see a reason to change anything in the nexus library, if it is not in the WAMP spec.

**Comment by gammazero** [comment]
No, there is anything like a "ProgressReceived" message sent back to the callee.  WAMP also does not allow sending error in response to YIELD message.

You may also consider using the Testament API to notify any callees of the disappearance of a caller.  On receiving a testament event, callees can stop sending progressive results to the disappeared client.

**Comment by gammazero** [comment]
related #131
