### ISSUE TITLE
Router panics with KeepAlive

### ISSUE THREAD

**Issue by HollowTooth** [gammazero/nexus#135]
Hi, 
I just recently added wss to the nexus router, and noticed, that the router panics, if `KeepAlive` is set (not 0).
This is related to one of my older issues here #99.
The problem, that I found, is that you cast the `net.Conn` to `net.TCPConn`, when with wss you have `*net.TLSConn`.
````
if s.KeepAlive != 0 {
	conn.UnderlyingConn().(*net.TCPConn).SetKeepAlive(true)
	conn.UnderlyingConn().(*net.TCPConn).SetKeepAlivePeriod(s.KeepAlive)	
}
````

**Comment by gammazero** [comment]
I will fix this within 12 hours (as soon as I have a moment this evening).  Will use websocket ping/pong as keepalive.

**Comment by gammazero** [comment]
@HollowTooth Fix is now merged.  A couple of other important fixes are included with latest merge, please update to latest version of nexus.

Thank you for reporting this problem.  It lead to a better way to handle the problem, as well as much more testing and improvements.
