### ISSUE TITLE
Websocket: Possibility to change the WS write channel length

### ISSUE THREAD

**Issue by ronanj** [gammazero/nexus#138]
in `websocketpeer.go`, the following constants are used:

```go
const (
	outQueueSize = 16
)
```

Is it possible to provide a way to modify this `outQueueSize` value?

**Comment by gammazero** [comment]
With the latest version of nexus, if the write channel is blocked, then the router will wait for a second to see if the message can be sent before dropping it.  So, if that ever happens, it means that the underling IPC is failing to buffer additional data.  Not sure that increasing the size would really help much.

I think the most technically correct thing to do is to set the size to 1 and rely on the short delay to wait for the kernel to buffer the waiting messages.  On a severely overloaded machine, it might be possible that the kernel is not able to buffer additional messages in time, but if this happens for more than a few messages, then something is wrong.  Having a channel size of 16 seems more than generous.  The situation may be slightly different when the peer is a local peer and does not have an underlying IPC mechanism (socket).

My concern here is that increasing the channel size will only mask the cause of the real issue.  If you have a particular case where messages are getting dropped, I would like to look into this to determine if changing the channel size really is the solution, or if this is the result of a larger issue.

**Comment by ronanj** [comment]
I agree on that increasing the size will only mask the real issue, so if the real issue can be solved then that would definitely be even better.

The example I am using is available in this commit: https://github.com/ronanj/nexus/commit/12dbf085cecea1ee6ad0d0fcaea950e0a5b95e12 

It consists of a NodeJs callee and Golang router/caller - where the callee tries to send as many messages as fast as possible. The error `!!! dealer dropped RESULT message: blocked` happens systematically when the callee sends the response back to the caller.

**Comment by gammazero** [comment]
I see that the version of nexus that you based your fork on does not have the fix for this issue, that I mention above.  You need to get the most recent version.  See if that fixes what you are seeing.

**Comment by ronanj** [comment]
Fixed with version 2.1.0. Thanks
