### ISSUE TITLE
Implementation of Server and Publisher in the same place

### ISSUE THREAD

**Issue by lyrixx** [gammazero/nexus#151]
Hello

I'm trying to create a server that read message from RabbitMQ and send them to clients using WAMP protocol.

I have read all examples, and some part of nexus lib.

But I don't see how I can implement that. It looks like I have to create 2 daemons, one for the server, and another one for publisher. Is there a way to create only one daemon ? I used to use react-php to do that, and It was possible. I would like to avoid creating 2 daemons because It adds more complexity (ops, go code, possible networking issue). I feel more natural to me to have one server that is able to push messages to client directly.

Thanks for your answer.

**Comment by gammazero** [comment]
If I understand what you are looking for, then yes it is not only possible, but also  primary design consideration of nexus.

With any router, you can also have as many embedded clients as you want.  The can be publishers, subscribers, callers and callees.  Making each client a connect to the router as a "local" client is the way for the client to communicate with the router without requiring any IPC or auth/authz.  The client is just another goroutine.

Here is an example of a router with an embedded callee:
https://github.com/gammazero/nexus/blob/master/examples/rpc/server_embedded_callee/server.go

That callee could just as well be a publisher, subscriber, or caller.

Router is created here:
https://github.com/gammazero/nexus/blob/master/examples/rpc/server_embedded_callee/server.go#L28

Callee client is created and connected to router here:
https://github.com/gammazero/nexus/blob/master/examples/rpc/server_embedded_callee/server.go#L40

You can create as many embedded clients as you like, using the [`client.ConnectLocal`](https://godoc.org/github.com/gammazero/nexus/client#ConnectLocal) method -- just another goroutine in your application.

**Comment by lyrixx** [comment]
Thanks for all you answer. Finally I have choosen to not use WAMP and so nexus. It adds too much complexity for my need. I use https://github.com/gorilla/websocket and that's all :)

Thanks again.
