### ISSUE TITLE
unable to Register & CALL procedure to crossbar router v18.10.1.post1

### ISSUE THREAD

**Issue by keiser1080** [gammazero/nexus#154]
Hi,

crossbar router raise protocol error:
i try the examples from github folder example in nexus repo
```
raise ProtocolError(u"{0}: invalid type {1} for WAMP extra".format(message, type(value)))
autobahn.wamp.exception.ProtocolError: 'options' in REGISTER: invalid type <class 'NoneType'> for WAMP extra

raise ProtocolError(u"{0}: invalid type {1} for WAMP extra".format(message, type(value)))
autobahn.wamp.exception.ProtocolError: 'options' in CALL: invalid type <class 'NoneType'> for WAMP extra
```

**Comment by gammazero** [comment]
Looks like there is a problem with having a nil value instead of an empty dictionary.  Will investigate and fix ASAP.

**Comment by keiser1080** [comment]
Thanks for your update!

just has the time to check .
now i am able to connect to a local crossbar server but not a remote crossbar server.

I will open an issue with ore detail.
