### ISSUE TITLE
unable to connect to remote crossbar

### ISSUE THREAD

**Issue by keiser1080** [gammazero/nexus#158]
hi,

refer to this issue #154 
i am able to run the  simple sucriber & simple publisher example when the crossbar server is located at the same linux server,
but when i try to connect to a remote crossbar server  i get the following error message: "Forbidden" on the nexus client application & nothing in the debug log of the crossbar instance.

[https://github.com/gammazero/nexus/tree/master/examples/simple](url)

here the crossbart config used:
```
 {
   "version": 2,
   "controller": {
   },
   "workers": [
      {
         "type": "router",
         "realms": [
            {
               "name": "realm1",
               "roles": [
                  {
                     "name": "anonymous",
                     "permissions": [
                          {
                              "uri": "",
                              "match": "prefix",
                              "allow": {
                                  "call": true,
                                  "register": true,
                                  "publish": true,
                                  "subscribe": true
                              },
                              "disclose": {
                                  "caller": false,
                                  "publisher": false
                              },
                              "cache": true
                          }
                      ]
                  }
               ]
            }
         ],
         "transports": [
            {
               "type": "websocket",
               "endpoint": {
                  "type": "tcp",
                  "port": 18080,
                  "version": 4,
                  "interface": "10.10.10.10"
               }
            }
         ]
      }
   ]
}
```

**Comment by martin31821** [comment]
Can you provide more details on the networking setup used? 
I see that your server is only listening on 10.10.10.10, maybe this is the problem.

**Comment by keiser1080** [comment]
I have two server.
the crossbar prod_server & the crossbar dev_server
the prod_server have multiple interface & ip_address it's why i specified the ip address.

if i run localy the  nexus client it's work on both server.
If i run the nexus client i can not reach the remote crossbar server, even if the ip is not specified on the crossbar config.
I use our simple susciber/publisher  example, i change only the ip address:

```
const (
        addr  = "ws://10.10.10.10:18080"
    //addr  = "ws://10.10.10.20:18080"
        realm = "realm1"

        exampleTopic = "example.hello"
) 
```
using the same config  i am able to connect using python client.
On the server side  there are nothing in the log even if i run crossbar with " --loglevel trace"

**Comment by martin31821** [comment]
I'm still convinced that this is a network level problem, since the connection isn't even reaching the crossbar router. Could you post the python code used to connect and (maybe) a pcap with python/go connections?

**Comment by keiser1080** [comment]
update:
using root privilege i am able  to suscribe to  a remote crossbar server.
I's realy strange, i am using the port 18080 wich is not a privilege port.

I have realy no idea, could you point my some direction.

I have not the right to install an application on this server.
Let me know if the pcap file is still needed i will prepare the same setup on others machine.

**Comment by gammazero** [comment]
The websocket client will automatically use the environment proxy:
https://github.com/gammazero/nexus/blob/master/transport/websocketpeer.go#L97

This can be changed by setting environment variables as described here:
https://golang.org/pkg/net/http/#ProxyFromEnvironment

However, the nexus client does not currently have a way to configure a proxy URL or proxy function.

If such a change is necessary, then I propose a new [`client.Config`](https://github.com/gammazero/nexus/blob/master/client/client.go#L37) option, `Proxy`, the specifies a URL to use.  If a value is provided for this option, then the client would use the result of [`ProxyURL()`](https://golang.org/pkg/net/http/#ProxyURL) instead of `ProxyFromEnvironment`

If that is sufficient, then I will create a PR for the feature.

**Comment by gammazero** [comment]
PR #161

**Comment by keiser1080** [comment]
Thanks for your reactivity , 

i will try this  as soon as i hundestand how to use it :)

**Comment by gammazero** [comment]
@keiser1080 To use it,  set `ProxyURL` in the `WsCfg` portion of the client config:
```go
    cfg := client.Config{
        Realm:  realm,
        Logger: logger,
        WsCfg: transport.WebsocketConfig{
            ProxyURL: "http://myproxyserver.com",
        },
    }
    // Connect client session.                                              
    cli, err := client.ConnectNet(addr, cfg)
   ...
```
