### ISSUE TITLE
Deadlock triggered by kill session meta procedure against sessions with registered procedure.

### ISSUE THREAD

**Issue by chongzizil** [gammazero/nexus#180]
I'm running into a deadlock problem recently.

Here's some context to reproduce the problem:
- The server's local client tries to close a remote client session by calling the session meta procedure: `wamp.session.kill`.
- The remote client session registers at least one procedure to the realm.

I've identified the problem as below:
1. The remote client connects and registers a procedure to the realm.
2. The local client calls the procedure: `wamp.session.kill`. Before completion, it sends a yield message to the `realm:r.metaPeer` and the meta session starts to process the message in `realm:handleInboundMessages`.
3. The remote client session exists `realm:handleInboundMessages` in `realm.handleSession` and calls `realm:onleave` method, which also calls `dealer.RemoveSession`. 
4. A message for `MetaEventRegOnUnregister` topic is sent to the `d.metaPeer` yet was blocked.

This leaves us with:
1. `goroutine_1-realm.go:handleInboundMessages`: the meta session tries to call Yield method which was blocked from pushing the action into the `dealer.go:actionChan`.
2. `goroutine_2-dealer.go:removeSession`: the ongoing dealer action tries to produce an event to `dealer.go:d.metaPeer` which was blocked by 1.

I'm not sure how to mitigate this issue or how to best fix it safely. For example, is it safe to run dealer actions in a separate goroutine?

Currently, I'm able to reproduce this easily in my own code base easily but I can't share that directly. Hopefully, my description above helps and If needed, I can try to write a small application to reproduce this.

**Comment by gammazero** [comment]
Thank you for the detailed description.  Fixing this ASAP.

**Comment by gammazero** [comment]
@chongzizil If you can confirm this is fixed, please close this issue.

**Comment by chongzizil** [comment]
@gammazero 

I just tested this and it works fine now! Thank you very much!
