### ISSUE TITLE
RPC example serialization problem with JSON

### ISSUE THREAD

**Issue by neiledgar** [gammazero/nexus#182]
I tried running the example code for the RPC caller/callee:

`go run server/server.go`
`go run rpc/callee/callee.go`
`go run rpc/caller/caller.go`

Both the callee and caller return a timeout message
```
CALLEE> timeout waiting for message
exit status 1
```
I then see the server process consume 100% CPU. If I repeat the test but specify `-serialize=msgpack` to the callee and caller, the example completes without error and without causing 100% CPU

`go run server/server.go`
`go run rpc/callee/callee.go -serialize=msgpack`
`go run rpc/caller/caller.go -serialize=msgpack`

I see this behaviour on Ubuntu 18.04.2

**Comment by gammazero** [comment]
Investigating...

**Comment by gammazero** [comment]
Originally, I could not reproduce this.  However, upon updating the json codec (`go get -u github.com/ugorji/go/codec`) I was able to get this error.

**Comment by gammazero** [comment]
Fixed by #186

**Comment by neiledgar** [comment]
Great. This also fixes issues I saw running the JSON encoding unit tests 

TestWSHandshakeJSON
TestRSHandshakeJSON

Thanks
