### ISSUE TITLE
Client lockup during Register() when session killed

### ISSUE THREAD

**Issue by neiledgar** [gammazero/nexus#183]
We are seeing a lockup in the client when the session is closed as the client is registering it's procedures. I could simulate this with an "wamp.session.on_join" procedure which calls "wamp.session.kill" for that session. After a few runs I see client never returns from the Register() method.

I generated a stack dump of the running goroutines and it looks like the client is blocked sending to the actionChan (client/client.go:477) but client run() goroutine has already exited.

With debug enabled the client logs are

$ go run rpc/callee/callee.go -serialize=msgpack
CALLEE> Connected to ws://localhost:8000/ws using msgpack serialization
CALLEE> Client 6882173603170586 received REGISTERED
CALLEE> Registered sum_0 as registration 31
CALLEE> Registered procedure sum_0 with router for client 6882173603170586
CALLEE> Client 6882173603170586 received REGISTERED
CALLEE> Registered sum_1 as registration 32
CALLEE> Registered procedure sum_1 with router for client 6882173603170586
CALLEE> Client 6882173603170586 received REGISTERED
CALLEE> Registered sum_2 as registration 33
CALLEE> Registered procedure sum_2 with router for client 6882173603170586
CALLEE> Client 6882173603170586 received REGISTERED
CALLEE> Registered sum_3 as registration 34
CALLEE> Registered procedure sum_3 with router for client 6882173603170586
CALLEE> Client 6882173603170586 received REGISTERED
CALLEE> Client 6882173603170586 received GOODBYE
CALLEE> Client 6882173603170586 closed

**Comment by gammazero** [comment]
Fixed by #184
