### ISSUE TITLE
Build fails with v2.1.0 (default version with go mod)

### ISSUE THREAD

**Issue by mullerch** [gammazero/nexus#185]
I've tried to run [the simple example](https://github.com/gammazero/nexus/blob/master/examples/simple/server.go) but it fails to compile:

> go build
> github.com/gammazero/nexus/transport/serialize
> [...]\go\pkg\mod\github.com\gammazero\nexus@v2.1.0+incompatible\transport\serialize\msgpackserializer.go:15:3: cannot use promoted field BasicHandle.DecodeOptions.RawToString in struct literal of type codec.MsgpackHandle

My configuration:
- go version go1.12.6 windows/amd64
- using go mod

And I have the exact same problem building with linux (WSL):
- go version go1.12.1 linux/amd64
- using go mod

**Comment by dcarbone** [comment]
use 2.1.2.  i do not know why go mod always picks 2.1.0 by default, but that version is only usable if you use something other than mod.

**Comment by mullerch** [comment]
Thanks for your reactivity. Effectively newest versions do compile.

**Comment by cameronelliott** [comment]
If you got here like me, because you got the error above, you might need to replace some of the import paths:

From/examples/out-of-date:
```
"github.com/gammazero/nexus/router"
"github.com/gammazero/nexus/wamp"
```

Fixed, up to date path for getting V3.x.x
```
"github.com/gammazero/nexus/v3/router"
"github.com/gammazero/nexus/v3/client"
"github.com/gammazero/nexus/v3/wamp"
```
