### ISSUE TITLE
Published methods with unpublished arguments

### ISSUE THREAD

**Issue by mullerch** [gammazero/nexus#187]
I wanted to access the broker on my server to publish messages from the server directly. I thought I could achieve this using router.Broker.Publish but this function uses router.session who is not exported.

I don't understand how exporting functions with non exported arguments makes sense. How is it supposed to be used ? Or is it a mistake?

**Comment by gammazero** [comment]
The way to publish messages from your server directly is to use a local client.  Here is an example:
https://github.com/gammazero/nexus/blob/master/examples/server/server.go#L149-L174

Use `client.ConnectLocal()` to connect to the router using the [local transport](https://github.com/gammazero/nexus/wiki/Transports#local-transport), which makes a direct in-process connection to the router.
