### ISSUE TITLE
Publish from the nexus host process

### ISSUE THREAD

**Issue by mullerch** [gammazero/nexus#188]
I have a use case where I would like to embed nexus in an application that will publish information to the subscribers. I was able to achieve this quite easily by publishing several structs and methods to reach a realm and it's broker.

I'm new to WAMP and nexus and I would like to know what would be a convenient way to implement that feature into nexus itself (regarding the WAMP philosophy and the nexus implementation) and/or if it's part of the uses cases goals / schedule of nexus.

**Comment by dcarbone** [comment]
I’m not sure I fully understand what you’re doing, but if you want a way to publish to specific topics from your wrapping service this should probably be done using a local client. 

I am on my phone, atm, but if you have a gander through the code you should see a LocalClient method that returns a WAMP client to be used as you see fit. By default, it is not scoped by the auth/auth mechanism for a Realm, but you can configure your Realm to require that if need be. 

-Daniel

**Comment by mullerch** [comment]
Thanks for your reply.

The local client is actually exactly what I'm talking about... I just couldn't find it. Now I'm wondering why it seems pretty obvious once you know where to look at.

Sorry for bothering.

**Comment by dcarbone** [comment]
No bother!  Happy to help.
