### ISSUE TITLE
go.mod missing v2 in module name

### ISSUE THREAD

**Issue by SnareChops** [gammazero/nexus#201]
Go 1.13

`go get github.com/gammazero/nexus@v2.1.3` fails with 

```
go: finding github.com v2.1.3
go: finding github.com/gammazero v2.1.3
go: finding github.com/gammazero/nexus v2.1.3
go: finding github.com/gammazero/nexus v2.1.3
go get github.com/gammazero/nexus@v2.1.3: github.com/gammazero/nexus@v2.1.3: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

According to my understanding of the go mod system the `go.mod` file in the nexus project should have the module declared as `github.com/gammazero/nexus/v2`

The error message posted above has been confirmed to be backwards by the go team, and they have submitted a patch. It states that it should *not* be v2, when it should state that it *should* be v2

Declaring nexus as a dependency with go 1.12 does not produce an error, but with 1.13 it appears the team has tightened compatibility requirements.

**Comment by dcarbone** [comment]
This package was at V2 prior to modules existing. It therefore has the +incompatible tag in go.mod. The upstream go.sum, part of go 1.13’s proxy implementation, does not support “incompatible” packages.

To fix the issue you’re currently seeing, add `github.com/gammazero/nexus` to your `GOPRIVATE` ennvar entry.

Moving to a whole new package path would be a good idea at some point, but that will get you going.

**Comment by gammazero** [comment]
@dcarbone Do you have a recommendation on the best (causes people the lease problems) way of handling this?  I would prefer not to move everything under a `nexus/v2` path, since the current repo is already v2.

What I want to do is simply change the version to 1.1.3, and pretend 2.x never existed.  However, I think that would cause more problems and confusion.  What would work best for you?

**Comment by dcarbone** [comment]
@gammazero: i have...many opinions on go modules, however i think the best solution would be this:

1. Leave v1 and v2 of nexus as-is
1. "Release" version `v3.0.0` with a `go.mod` entry of `github.com/gammazero/nexus/v3`.

I suggest this for a few reasons:

1. As you correctly identify, forcing existing users of v2 to add a `/v2` suffix to each reference of nexus is a big ask (and, to be blunt, a pain in the ass)
1. I think going to a LOWER version number would just cause massive headaches for all.
1. Creating a new `v3.0.0` tag _shouldn't_ trip up any non-go-modules-using individuals (glide, dep, etc.) that are using sensible semantic versioning values (i.e. using `v2.1.*` or something as their requirement)
1. A major version update is about the only time it is acceptable to require package path changes, imo, which is require to follow proper versioning with modules
1. It must be clearly stated and understood that, going forward, this repository will follow the versioning standards put forth by the go team.
1. We can hang out in `/v3` for....forever, basically.  there is nothing saying that each release needs to be `/v4`, `/v5`, etc.  Those should be reserved for breaking changes / massive updates that require significant code change by users to use.  Totally valid to have `/v3` path and release tags `v3.0.1`, `v3.0.2`, `v3.1.0`, etc.

Let me know if that makes sense. That is the path I am taking with my own projects internally, and so far the results have been...acceptable.

**Comment by gammazero** [comment]
That seems like the most reasonable approach after reviewing recommended versioning standards.  So, that being the plan, this would be a great time to implement any compatibility-breaking changes.  If we want to rework the client API, that could be done now.

**Comment by dcarbone** [comment]
I agree. Unfortunately I've not had a chance to work on the updated client interface much :\

**Comment by gammazero** [comment]
Here is the new v3 branch that fixes this issue as well as makes a number of breaking changes that clean up APIs.  See if [these changes](https://github.com/gammazero/nexus/commit/2f3ded7c0577b7b274912c98ce60edeff3d4594c) look reasonable, and I will tag the v3 branch as `v3.0.0` and make it the default branch.  If there are other breaking changes that you want, now if the time to suggest them.

**Comment by gammazero** [comment]
@martin31821 I am going to release nexus v3.  This is a major version revision, and has breaking [changes](https://github.com/gammazero/nexus/commit/2f3ded7c0577b7b274912c98ce60edeff3d4594c) resulting from API refactoring and cleanup. If you have some time, please let me know if there are additional changes you thing should be made as part of a v3 release.

**Comment by dcarbone** [comment]
@gammazero: i’m currently in the middle of the mediterranean without decent access to internet, i can have a look after i get back to land later this week.

**Comment by martin31821** [comment]
@gammazero looks good, I don't see more required breaking changes.
We can do additions to the existing API in minor versions, so I think we should be good to go here.

**Comment by SnareChops** [comment]
@gammazero Closing as resolved with v3
