### ISSUE TITLE
[Feature request] Include version number/git hash in Nexusd build

### ISSUE THREAD

**Issue by kuema** [gammazero/nexus#203]
Is it possible to include the current version number (latest git tag) and/or the git hash into the build somehow?

That information could then be printed to the console on start-up, something like:

`2019/10/08 09:08:12 Starting router; version v2.1.3; git 2b9db9a`

We are running Nexusd on several machines now, but - besides from proper documentation (of course 😃) - you can never be sure which version of Nexusd you are actually running.

I am not familiar with the Go build system, so I cannot assess if or how this could be implemented.

**Comment by gammazero** [comment]
Done.  Build using `make`.  Running nexusd logs server version when starting.  You can also print the version by: `nexusd -version`

https://github.com/gammazero/nexus/commit/bce0601c2dfc91b9b8952514b16124c398d63abe

**Comment by kuema** [comment]
Works as expected. I think we can close this one. 

Thank you!
