### ISSUE TITLE
No way to enable websocket ping/pong from client

### ISSUE THREAD

**Issue by neiledgar** [gammazero/nexus#206]
We have a scenario where the network between the websocket client and the router is lost. The router detects this failure quickly because we set the WebsocketServer.KeepAlive. However, the client takes much longer and falls back to the TCP connection keep alive.

There appears to be no way to configure the websocket ping/pong from the client. You mentioned this might be considered https://github.com/gammazero/nexus/issues/189#issuecomment-512985000

If agreeable, I will create pull request to add WebsocketConfig.KeepAlive and pass this into NewWebsocketPeer() 

https://github.com/gammazero/nexus/blob/master/transport/websocketpeer.go#L158

**Comment by gammazero** [comment]
Resolved by #207
