### ISSUE TITLE
Calling a progressive rpc function registered with autobahn does not work

### ISSUE THREAD

**Issue by ickby** [gammazero/nexus#208]
Hello,

I have a client written in python with autobahn, that registers a rpc function utilizing progressive results. However, it fails to deliver the progressive results when I call this function from a  nexus client. Both are connected via the nexus router.

I made a little hacked example. This [nexus code](https://gist.github.com/ickby/4c9cb98410bd7909f36d15e43f915c1b) should work with the default autobahn [callee](https://github.com/gammazero/nexus/blob/v3/examples/interop/autobahn-python/sub_callee.py) in the example folder. It does succeed in calling the method, however, on autobahn side the "progress" entry in details is empty. (one needs to start the go program first and within the next 5 seconds the python calle)

Is this a know issue? Any idea how to solve this?

**Comment by gammazero** [comment]
@ickby I ran you example code _exactly as is_ and it worked perfectly.  Everything looks good in both the nexus and autobahn client.  Perhaps something was fixed on in one of the code bases allowing this to work.  There is no fix, that I am aware of on the nexus side, that would have made this work.

I have also updated the [interop autobahn-python](https://github.com/gammazero/nexus/tree/v3/examples/interop/autobahn-python) examples to include a nexus client that can be run against the autobahn client.  You can also drop [your code](https://gist.github.com/ickby/4c9cb98410bd7909f36d15e43f915c1b) directly into that directory and run it as well.

**Comment by gammazero** [comment]
Please see the examples noted above and retest with the latest version of nexus (v3.0.2). As far as I can confirm, this issue is fixed and working with your examples.  If there is still a problem, please reopen issue.
