### ISSUE TITLE
Is any work being done to create a HA wamp client

### ISSUE THREAD

**Issue by bkneis** [gammazero/nexus#218]
Reading the [following page](https://github.com/gammazero/nexus/wiki/High-Availability) in the wiki, there seems to a design to allow a "federated wamp client" to connect to multiple redundant wamp routers. Is there any work being / been done on this?

Many Thanks

**Comment by u774r4v4d1n** [comment]
@bkneis @gammazero still waiting on this.

**Comment by gammazero** [comment]
@bkneis Not to my knowledge.  So far there has been very little ask for building this into the nexus router itself.  If there was sufficient interest, then I think this would be a great extension to nexus, probably best done as a separate project, at least initially.

**Comment by gammazero** [comment]
There is some renewed interest in exploring HA solutions, and I will direct those discussions to #144. This includes any discussion of the federated WAMP client, or federated WAMP routers.  So, I am closing this issue to keep these discussions on #144 .
