### ISSUE TITLE
RAM memory usage

### ISSUE THREAD

**Issue by benk79** [gammazero/nexus#231]
I am facing a memory usage issue. In fact memory usage goes up, but never down even if disconnecting all clients.

Tests are done on a debian server where i set up nexusd as service. At beginning memory usage is very low. Try connecting 3k clients, then block the clients (dirty exit on clients). Memory usage never comes down. Is it due to dirty exits of clients or not, i don't know.

This is my configuration:

```
{
    "websocket": {
        "address": ":8080",
        "cert_file": "",
        "key_file": "",
        "keep_alive": 30,
        "enable_compression": false,
        "allow_origins": ["*"]
    },
    "rawsocket": {
        "tcp_address": "",
        "tcp_keepalive_interval": 180,
        "unix_address": "",
        "max_msg_len": 0,
        "cert_file": "",
        "key_file": ""
    },
    "log_path": "/var/log/nexus/nexus.log",
    "router": {
        "realms": [
            {
                "uri": "aizocloud",
                "strict_uri": false,
                "allow_disclose": true,
                "anonymous_auth": true,
                "meta_strict": false,
                "meta_include_session_details": [],
                "enable_meta_kill": true,
                "enable_meta_modify": false
            }
        ],
        "debug": false
    }
}
```

**Comment by gammazero** [comment]
Memory should eventually be returned, when GC reclaims it.  If you are not seeing memory use decrease, then perhaps there is an issue that I need to investigate.   Please help me look into this by answering the following questions:

1. How are you disconnecting your clients?  Sending GOODBYE message, killing process, other?
2. What client are you using (nexus, autobahn, etc.).
3. What transport are you using? Websocket, tcp, unix, tls enabled, local (no transport),?
4. Are you doing any sort of authentication within WAMP?
5. Are you using the latest v3 version of nexus?

**Comment by gammazero** [comment]
Are you looking at memory allocated to the process or by memory used within the process?  If you are then you may not see much if any memory returned to the OS.  Here is an explanation:
https://utcc.utoronto.ca/~cks/space/blog/programming/GoNoMemoryFreeing

When periodically sampling memory stats in the router, I do see memory reclaimed:
```
Mallocs: 1071901
Frees: 1048827
HeapAlloc: 3408288
NumGC: 49

Mallocs: 1071906
Frees: 1069181
HeapAlloc: 705168
NumGC: 50
```
Notice `HeapAlloc` goes from 3408288 to 705168. After running hundreds of clients, it stayed around the the first value for a minute or so, then dropped down to the second.  I am using [`runtime.ReadMemStats`](https://golang.org/pkg/runtime/#ReadMemStats) to get this periodically.

I will look at stats over a longer time period to see if there appear to be any leaks, but it looks like GC is working.

**Comment by benk79hes** [comment]
1. How are you disconnecting your clients? Sending GOODBYE message, killing process, other?
    ->  I noticed the problem making test which were killing the process, but then also tested with clean closing with goodbye, and the problem was still there, exactly the same.

2. What client are you using (nexus, autobahn, etc.).
    -> I am using autobahn js and autobahn python.

3. What transport are your clients using? Websocket, tcp?
    -> websocket

4. Are you using the latest v3 version of nexus?
    - I think so (got it from github about 15 days ago. Will have a check on next monday as i am off and not connected to test server until then.

5. Are the clients subscribing to event topics or registering for RPC?
   - Only RPC for tests done until now

6. Are clients publishing events or making RPC calls?
   - Only RPC for tests done until now


About memory usage i am looking at the process with top command.

I am not used to golang, so i don't know were to go for checking it from the router itself... I came on your project because we plan to connect about 10k devices to our cloud, and first tests shows that what you did is really great stuff for using more CPU's compared to crossbar :-) . If you can tell me how to make other tests from router side i will perform them next week.

Thank you

**Comment by gammazero** [comment]
It looks like the router memory use eventually returns to about where it started, regardless of how clients disconnect.  Tested with nexus and autobahn clients.  PR #233 added the ability for the router to log memory stats periodically.  See [MemStatsLogSec](https://godoc.org/github.com/gammazero/nexus/router#Config) in the router config.  You can use this to track memory allocation over time.  You may also want to run with `GODEBUG=gctrace=1`

Please let me know if the memstats logging shows heap allocation that keeps growing indefinitely, when given sufficient time for GC to do its job, and I can investigate further.  If you see no leakage, you can close this PR.

**Comment by benk79hes** [comment]
Thanks to you @gammazero, i will definitely validate it by next monday, but i am confident it will be ok. I will not miss to confirm.

**Comment by gammazero** [comment]
After doing some memory profiling, I still did not see any major leaks.  However, I was able to make an improvement by reducing the number of allocations of empty types.  This is part of nexus v3.02..,

**Comment by benk79** [comment]
@gammazero I do confirm HeapAlloc is going down with GC. However i had to add this in the code as your PR does not show it.

`r.log.Printf("MemStats: Alloc=%d Mallocs=%d Frees=%d NumGC=%d", m.Alloc, m.Mallocs, m.Frees, m.NumGC)`
