### ISSUE TITLE
emptyDict implementation introduces problems

### ISSUE THREAD

**Issue by dcarbone** [gammazero/nexus#235]
The new `emptyDict` implementation is dangerous as it means that if a local peer connected to a realm modifies a field in a message that has been set to the `emptyDict` var, it changes the state of the entire server.

I have created a test for this illustrating the problem, and will add a PR for it.  I would recommend reverting this change.

**Comment by dcarbone** [comment]
PR #236 provides a test with simple illustration of the problem.

**Comment by gammazero** [comment]
There was an assumption that local clients would not alter message contents, and being local clients that are trusted, they can be trusted to behave. Maybe this is not a safe assumption.

If we want to allow local clients to alter message contents, this also means there will need to be some changes to things like publishing the same event to multiple clients, or calling RPC that goes to multiple clients.

Do you prefer to allow local clients to alter message contents, at the expense of having to make copies of data, or do you thing is it reasonable to have a rule that states that a local client may not alter message content as that may corrupt the message received by other clients?

**Comment by dcarbone** [comment]
1. My primary concern is that it _is_ possible, and therefore it is very likely it is being done by somebody somewhere.  Introducing this change could and probably will cause issues for these people.
1. I haven't spent the time to track everywhere this may cause issues, but given all of the (very useful, mind you) meta calls you have added as part of the Nexus implementation, the side effect of this could be very weird in symptom and difficult to diagnose should an implementor be taking advantage of this possibility.

Ultimately: This seems like premature optimization.

I feel like either letting the maps remain nil or creating new maps each time are the only two allowable implementations here.

To prevent further regressions, however, I think the only acceptable solution at this point is to always test for and create distinct dicts per message when they're empty.  This does increase memory pressure a little bit but it ensures, to the best of our ability, that the memory of each message is contained to only that message (implementors can, ultimately, do whatever they damn well please).

I would be interested in seeing your pprof output to see if we could potentially identify a less side-effect heavy reduction in gc pressure.

**Comment by gammazero** [comment]
I agree with your assessment, and will revert the changes having to do with emptyDict.  Additionally, local clients will make copies of the event arguments so that changes to those do not affect other clients (test confirms this is a problem as well).

**Comment by dcarbone** [comment]
Awesome, man.  Thanks for all your hard work on this implementation!

**Comment by gammazero** [comment]
Thank you very much for catching this issue and responding quickly.  This was a huge help!

We can follow up with memory profiling in a separate issue.
