### ISSUE TITLE
client connection gets dropped due to it being unable to reply to a socket ping

### ISSUE THREAD

**Issue by DewitteRuben** [gammazero/nexus#245]
Setup:
- Raspberry Pi running the WAMP client and Docker, connected to a Crossbar instance
- RPC calls are used to start/stop docker builds/pulls/runs

It seems that, from what I've seen, that the client is blocked and with that unable to reply to a ping from the socket in question (a crossbar instance in this case). This causes the client to receive a Done signal forcing me to re-establish the socket connection.

It seems to only occur when the client busy in some kind of way

Some ideas I had that might cause this issue:
- Client is busy handling doing something (e.g. handling an RPC call), and is unable to respond to the ping
  - The issue only seems to occur whenever an additional RPC is being called, so maybe the client is being blocked in some way or another?
- Device runs out of resources and is unable to respond to the ping
  - Kind of doubt this reason since upon viewing CPU usage of device, it seems to have CPU / RAM to spare

Things we have tried, besides going over the code multiple times:
- Setting niceness to the executable running the WAMP client
- Shaping the network traffic to prioritize that of the client
- Making sure nothing is blocking an RPC handler / the client in any way

Any kind of help or hints would be appreciated..

**Comment by gammazero** [comment]
If you have control of the server, disabling websocket keep-alives may be a temporary solution.  Seems similar to this: https://github.com/gorilla/websocket/issues/97

So, I may need to replace the ping handler as described [here](https://github.com/gorilla/websocket/issues/97#issuecomment-194967563).

**Comment by DewitteRuben** [comment]
@gammazero Thanks for the reply!

Sadly, the temporary solution of disabling the keep-alive is not an option for us. We currently use the keep-alives to toggle a 'device' it's connection status in our database. So we need our crossbar instance to be aware if one of our clients has an active connection or not.

The issue you're referring would explain the behavior we are experiencing, might take a look into that to see if that's actually the cause.

**Comment by gammazero** [comment]
If you can try PR #247 and see if that fixes the situation for you, then I can merge that if that is the solution.

**Comment by DewitteRuben** [comment]
@gammazero Thanks a lot for the effort, and reaction time.

Unfortunately it seems that this did not resolve the issue. With further investigation it seems like this issue does not occur when there the internet connection is established with ethernet, so it might just be related to some OS configuration, the Raspberry Pi's WiFi hardware, or maybe a power issue under heavy CPU load. I also can't reproduce the issue when trying the executable on my mac.

If you want you can close this issue because it might not be related to the client itself. Unless you have any other ideas...

**Comment by gammazero** [comment]
I will leave the PR open until I have time to evaluate whether it offers help in any situation.  As for your case, maybe try enabling keep-alives on the client side.  Even though the incoming pings are not getting through, maybe outgoing pings would keep the connection alive.

To enable client-side keep-alives, set the `WsCfg.KeepAlive` in the client config:
https://github.com/gammazero/nexus/blob/v3/client/config.go#L71
https://github.com/gammazero/nexus/blob/v3/transport/websocketpeer.go#L45

**Comment by DewitteRuben** [comment]
Thanks for the suggestion, Sadly, also have tried that, to no avail. 😦 
Will post an update here when we figure out exactly why...

**Comment by DewitteRuben** [comment]
I think the ping changes actually fixed the issue, maybe I had incorrectly applied the patch back then.
In any case, since I updated our go dependencies to their latest version, (so also the nexus client to 3.0.4), I cannot seem to reproduce this issue anymore, so I'm going to close it for now. Thanks
