### ISSUE TITLE
client: WAMPCRA with salting is broken

### ISSUE THREAD

**Issue by om26er** [gammazero/nexus#252]
Using Crossbar as WAMP router and the Nexus client library, I can connect to Crossbar when using WAMPCRA without salting. If salting is enabled, the Nexus client library fails to connect.

autobahn-python is able to connect to Crossbar successfully, so I believe the issue lies somewhere in Nexus.

**Comment by om26er** [comment]
Here is how we are using CRA https://github.com/codebasepk/wick/blob/6f390db0745744eb66ab190db6fce67bbe9cdab5/wamp/main.go#L119

**Comment by gammazero** [comment]
@om26er Thank you for this analysis of the problem.  I have applied your fix in PR #255.

**Comment by gammazero** [comment]
If latest change fixes this issue, please close PR.

**Comment by oberstet** [comment]
@om26er ^?

**Comment by om26er** [comment]
Fixed, thanks for taking care of that
