### ISSUE TITLE
Router returns an ABORT message with the wrong parameters

### ISSUE THREAD

**Issue by jschmid** [gammazero/nexus#253]
The WAMP specification says that the ABORT message should send a dictionary with a `message` key.
https://wamp-proto.org/_static/gen/wamp_latest.html#abort-0

Most of the implementations I have found comply with it:

* [WampSharp](https://github.com/Code-Sharp/WampSharp/blob/82a672e38cdf9489968d66d8b18a926cfd198ff7/src/netstandard/WampSharp/WAMP2/V2/Authentication/WampAuthenticationException.cs#L23)
* [Autobahn JS](https://github.com/crossbario/autobahn-js/blob/bd250753432a7bc61b7b7dae1df5fc70ddedcad6/packages/autobahn/lib/connection.js#L305)
* [Autobahn Java](https://github.com/crossbario/autobahn-java/blob/3b244734d7396810a5a60539b98c58fa379f6cd9/autobahn/src/main/java/io/crossbar/autobahn/wamp/messages/Abort.java#L40)
* [Crossbar](https://github.com/crossbario/crossbar/blob/e8f546be14b3b2b8e96c3d185f3330022fbcc892/crossbar/worker/proxy.py#L220)

However, Nexus does not send the correct dictionary. It sends the dictionary with an `error` key. https://github.com/gammazero/nexus/blob/775c9a891beb1199468ca49b73f245ae02bf7075/router/router.go#L135

Note that we also have it here: https://github.com/gammazero/nexus/blob/775c9a891beb1199468ca49b73f245ae02bf7075/router/realm.go#L408

Is there a reason why Nexus sends this key instead of `message`? Can we change this?

**Comment by gammazero** [comment]
It was compliant with an older version of the protocol spec.  I will update it.

**Comment by jschmid** [comment]
Thanks!
