### ISSUE TITLE
How to describe Specific(CryptoSign, Ticket) Authentication for Router?

### ISSUE THREAD

**Issue by Mahad-10** [gammazero/nexus#256]
I am running nexus router and i want to describe specific authentication type for a realm. I couldn't find anything in the nexus.json file.

**Comment by gammazero** [comment]
An example of specifying an authenticator for the router to use is [here](https://github.com/gammazero/nexus/blob/v3/aat/main_test.go#L136).

The router is configured with a list of [Authenticator](https://github.com/gammazero/nexus/blob/v3/router/auth/authenticator.go#L22) interfaces.
