### ISSUE TITLE
Move to another WebSocket Library as gorilla/websocket is not supported anymore

### ISSUE THREAD

**Issue by KSDaemon** [gammazero/nexus#292]
gorilla/websocket was a great WS implementation! But for quite a long time it is not supported at all. Even small bug fixes are not merged and still waiting for miracles. 

But there are new and even better WS implementations around. We should choose and try to use one of those.

I know that @om26er has a pretty good experience with [nbio](https://github.com/lesismal/nbio) if I'm right.

**Comment by gammazero** [comment]
Looks like gorilla/websocket is being actively maintained again. Lets stay with it unless there is a really compelling reason to switch.

**Comment by gammazero** [comment]
Closing, as support for gorilla has resumed.
