### ISSUE TITLE
Modify WebsocketServer Tracking Cookie Attributes

### ISSUE THREAD

**Issue by mjkrivacek** [gammazero/nexus#295]
**Is your feature request related to a problem? Please describe.**
Using the websocket server with web browsers causes inconsistent behavior with using tracking cookies because of the attributes (or lack of) for the cookie. 

**Describe the solution you'd like**
I would like the ability to modify the http.Cookie attributes presented by the websocket server when tracking cookies are enabled.  Specifically the ability to set `Secure: true` and `SameSite: http.SameSiteNoneMode`

**Describe alternatives you've considered**
For now, we are cloning the project, hard coding the http.Cookie settings in `func (s *WebsocketServer) ServeHTTP(w http.ResponseWriter, r *http.Request)` and redirecting in go.mod.

**Additional context**

**Comment by gammazero** [comment]
Would you be willing to provide a PR to this project? Seems like it would be a useful addition.

**Comment by mjkrivacek** [comment]
I can try.  I've never contributed to a public project so I'll need to figure out how to do that correctly.

**Comment by KSDaemon** [comment]
@mjkrivacek Great! Don't worry! We'll help you! 
Just fork this repo, introduce code changes, cover them with tests, describe new feature in the docs (maybe add examples) and create a Pull Request against this upstream! And assign/mention us for the review. We can discuss all the things in that PR, you can fix something if needed, PR will be updated automatically with the latests changes in your fork. 
In any case feel free to ask us!
