### ISSUE TITLE
Crossbar.io config JSON

### ISSUE THREAD

**Issue by lajosbencz** [gammazero/nexus#60]
Hello, thanks for this awesome library!

We've been using crossbar.io as our router, but i have my concerns about it's performance.
We would like to use nexusd instead, but I cannot find reference on how to register an authenticator.

I'd like to replicate this crossbar config with nexusd:

```json
      "transports": [
        {
          "type": "websocket",
          "endpoint": {
            "type": "tcp",
            "port": 8090
          },
          "auth": {
            "wampcra": {
              "type": "static",
              "users": {
                "auth": {
                  "secret": "<some shared secret>",
                  "role": "auth"
                },
                "server": {
                  "secret": "<another shared secret>",
                  "role": "server"
                }
              }
            }
          }
        },
        {
          "type": "websocket",
          "endpoint": {
            "type": "tcp",
            "port": 8080
          },
          "auth": {
            "wampcra": {
              "type": "dynamic",
              "authenticator": "auth.login"
            }
          },
          "cookie": {
            "max_age": 86400,
            "store": {
              "type": "memory"
            }
          }
        }
      ]
```

ANY help is appreciated!

**Comment by lajosbencz** [comment]
I've since noticed that cookie auth is unsupported, please ignore that part of the config

**Comment by gammazero** [comment]
Currently the AAT code is where examples can be found (yes, proper exampled coming soon).  Here you can see a `RouterConfig` that registers a challenge-response authenticator:
https://github.com/gammazero/nexus/blob/master/aat/main_test.go#L119-L121

It is created here:
https://github.com/gammazero/nexus/blob/master/aat/main_test.go#L100

The test authenticator implementation is here:
https://github.com/gammazero/nexus/blob/master/aat/auth_test.go#L152-L176

I will be happy to work with you to help get this working or provide additional functionality that you may need.  That being said...  I am considering PR #59 that will change the source layout, but otherwise not affect APIs.  If that looks good to you, I can merge that now so you will not need to make any changes to your code to get updates.

**Comment by lajosbencz** [comment]
Since the changes are pedantic improvements (moving router into its own namespace?), it really doesnt matter for me... :]

**Comment by lajosbencz** [comment]
Since the changes are pedantic improvements (moving router into its own namespace?), it really doesn't matter to me... :]

I haven't written any serious go code yet, so my aim here would be to create a small wrapper app that can interface between the crossbar-style config and nexus router. It would be really neat if one could seamlessly migrate from crossbar to nexus.

**Comment by ajgillis** [comment]
Nexus currently does not have much in terms of authenticator configuration.  Currently, you define your `Authenticator` or `CRAuthenticator` implementation and provide it to the router.  You have to do _all_ the work to implement an authenticator, including JSON encoding the `Challenge.Extra["challenge"]` string (which AAT example does not do).  It would be nice to have code that did that for the implementor.

Having something that specifies user setup, secret definition, etc. in a configuration structure could be very useful.  I will look at providing that.  Perhaps the wrapper that you create could serve as a starting point?

**Comment by gammazero** [comment]
Nexus currently does not have much in terms of authenticator configuration. Currently, you define your Authenticator or CRAuthenticator implementation and provide it to the router. You have to do all the work to implement an authenticator, including JSON encoding the Challenge.Extra["challenge"] string (which AAT example does not do). It would be nice to have code that did that for the implementor.

Having something that specifies user setup, secret definition, etc. in a configuration structure could be very useful. I will look at providing that. Perhaps the wrapper that you create could serve as a starting point?

**Comment by lajosbencz** [comment]
Hopefully, yes, but give me some time, i still have to figure at some basic go concepts :]

Maybe an adapter ~~class~~ interface for config files would be the most useful, so any wamp router config could be easily migrated.

**Comment by gammazero** [comment]
OK, so major overhaul of authenticators!  What was there before was really not correct.  This is much simpler.  Please see this first:
https://github.com/gammazero/nexus/pull/61

**Comment by gammazero** [comment]
To implement a wampcra authenticator, all that really need to be done on the router side is to define a `KeyStore`.  Here is an example:

```go
type serverKeyStore struct {
    provider string
}

func (ks *serverKeyStore) AuthKey(authid, authmethod string) ([]byte, error) {
    if authid != "jdoe" {
        return nil, errors.New("no such user: " + authid)
    }
    switch authmethod {
    case "wampcra":
        // Lookup the user's key.                                               
        return []byte("squeemishosafradge"), nil
    case "ticket":
        // Lookup the user's key.                                               
        return []byte("ticketforjoe1234"), nil
    }
    return nil, nil
}

func (ks *serverKeyStore) PasswordInfo(authid string) (string, int, int) {
    return "", 0, 0
}

func (ks *serverKeyStore) Provider() string { return ks.provider }

func (ks *serverKeyStore) AuthRole(authid string) (string, error) {
    if authid != "jdoe" {
        return "", errors.New("no such user: " + authid)
    }
    return "user", nil
}
```
Then configure the router:
```go
crAuth, err := auth.NewCRAuthenticator(&serverKeyStore{"static"}, time.Second)
if err != nil {
    t.Fatal(err)
}
config := &router.RouterConfig{
    RealmConfigs: []*router.RealmConfig{
    {
        URI:            wamp.URI("nexus.test.auth"),
        Authenticators: []auth.Authenticator{crAuth},
    },
}
nxr, err = router.NewRouter(routerConfig, nil)
```

**Comment by gammazero** [comment]
The client implementations is essentially unchanged.  The only difference is that you no longer need to write your own signing function, as one is provided now.

With a nexus client, define a function that gets when a challenge is received:
```go
func clientAuthFunc(d wamp.Dict, c wamp.Dict) (string, wamp.Dict) {
    ch := wamp.OptionString(c, "challenge")
    // If the client needed to lookup a user's key, this would require decoding
    // the JSON-encoded ch string and getting the authid. For this example      
    // assume that client only operate as one user and knows the key to use.    
    key := "squeemishosafradge"
    sig := crsign.SignChallenge(ch, []byte(key))
    return sig, wamp.Dict{}
}
```
Then use that to configure a client:
```go
    cfg := ClientConfig{
        Realm: "nexus.test.auth",
        HelloDetails: wamp.Dict{
            "authid": "jdoe",
        },
        AuthHandlers: map[string]AuthFunc{
            "wampcra": clientAuthFunc,
        },
        Logger: logger,
    }
    client, err := ConnectLocal(r, cfg)
```

**Comment by gammazero** [comment]
While this does not constitute a wrapper or adaptor for crossbar config, it should make is far easier to provide one.

**Comment by lajosbencz** [comment]
Much-MUCH easier, awesome, thank you!

**Comment by gammazero** [comment]
I have not done interop testing yet, so if you run into any issues before I do, let me know and I will fix ASAP.

**Comment by gammazero** [comment]
I have cleaned up the reworked Authenticator API, and made a small change to the client.  The API changes are now done, and have resulted in a new major release: https://github.com/gammazero/nexus/releases/tag/v2.0

You will probably want to get the updates, but they should pretty close to what you are already working with.

Not sure that including an Authbahn compatibility API as part of the nexus router is the right thing to do, but having a separate adaptor package would probably be very beneficial.  If that is the way to provide that functionality, then you can offer that through your own repo, or I can include it as a utility in the nexus repo.

**Comment by gammazero** [comment]
I am going to propose closing this issue since the reworked challenge-response API should allow for a relatively simple Autobahn adaptor to be put in place for the router.

**Comment by lajosbencz** [comment]
Okay, i'll let you know if i have a working solution!
