### ISSUE TITLE
SignChallenge using PBKDF2? 

### ISSUE THREAD

**Issue by crabicode** [gammazero/nexus#66]
Is it possible to add support for PBKDF2?

**Comment by gammazero** [comment]
That should be possible. I will look into adding that.  Are you asking for this to be build into nexus, or are you asking for the API to change to make is easier to add your own challenge signing implementation?

**Comment by gammazero** [comment]
I am adding PBKDF2 which will be used automatically if password salting info is provided with the challenge message.  The `KeyStore` API already supports salting data, and the `CRAuth` API already includes that in the challenge message:
https://github.com/gammazero/nexus/blob/master/router/auth/crauth.go#L61-L66

**Comment by gammazero** [comment]
To address the need for clients to deal with using PBKDF2 to create derived keys, from password and salting info, and then sign the challenge from the router, I have created a new utility function `crsign.RespondChallenge()` that takes a password and a CHALLENGE message.   If the CHALLENGE contains salt info, then the challenge string is signed with a key created using PBKDF2.

This is implemented in PR 68: https://github.com/gammazero/nexus/pull/68

**Comment by gammazero** [comment]
PR merged. API documented here: https://godoc.org/github.com/gammazero/nexus/wamp/crsign#RespondChallenge
and in wiki:
https://github.com/gammazero/nexus/wiki/Auth-Library#client-side-authenticator

Closing issue.
