### ISSUE TITLE
Expose upgraded request

### ISSUE THREAD

**Issue by crabicode** [gammazero/nexus#67]
Is it possible to expose upgraded request to session's details so that one could get meta from the request itself?

For example, it can enable cookie-auth, ip filtering and etc

**Comment by gammazero** [comment]
In nexus, the session meta API `session_get` does return all session details, not just those prescribed by WAMP.  See here:
https://github.com/gammazero/nexus/blob/master/router/realm.go#L686-L691

This allows you to do some very interesting things, especially when used with the authorizer to inject custom content into the session details.  See comment here:
https://github.com/gammazero/nexus/blob/master/router/authorizer.go#L12-L17

You can use these features to write advanced client-side filter logic.

**Comment by gammazero** [comment]
For cookie-based auth, a random cookie could be assigned to the client, by providing a response header when upgrading the connection here:
https://github.com/gammazero/nexus/blob/master/router/websocketserver.go#L136
The cookie value can be set in the `websocketPeer` or passed to `router.Attach()` here:
https://github.com/gammazero/nexus/blob/master/router/websocketserver.go#L184

Once the client successfully authenticates, the router could store the authentication information and use the client's cookie value as a lookup key.   When the client returns later, and sends the cookie previously assigned, the router will look up the cookie, and if the cookie has attached authentication information, the router will immediately authenticate the client using the previously stored information.

This is how crossbar.io does cookie authentication.  It requires activating cookie-tracking and at least one non-cookie based authentication method.

If this what you are asking for?  Or, are you asking that cookie data, IP address, etc., provided by the transport, be injected into the session details and be retrievable by getting session meta?

**Comment by azamat-sharapov** [comment]
> Once the client successfully authenticates

How do you suggest to catch "successful auth"? I think we should have some hook for it.

**Comment by azamat-sharapov** [comment]
> I think we should have some hook for it.

@gammazero do you accept PR for this?

**Comment by gammazero** [comment]
@azamat-sharapov If you have a PR or a design in mind, then let's figure out how best to do this.

**Comment by azamat-sharapov** [comment]
@gammazero I was thinking to extend `KeyStore` interface with a func (say, `OnWelcome`) and call it after successful login ([crauth](https://github.com/gammazero/nexus/blob/master/router/auth/crauth.go#L101), [ticket](https://github.com/gammazero/nexus/blob/master/router/auth/ticket.go#L87)). It could accept `welcomeDetails`. What do you think?

**Comment by gammazero** [comment]
@azamat-sharapov Extending the KeyStore seems reasonable.  Wondering is some larger change in the auth interfaces is needed.

 > Could you please hint, how can I pass cookie value to the router?
I was thinking that the router would look for a specific cookie (having a documented name) in the request headers, and then use the cookie's value to look up auth information.

**Comment by azamat-sharapov** [comment]
@gammazero I think we still need to expose handshake request to KeyStore somehow.. Here is how I imagine cookie auth:

1. When upgrading to WS, we write random cookie to Response
2. Client tries to auth (CR or ticket) and on successful auth, we call `OnWelcome(welcomeDetails, handshakeRequest)` (plz mind `handshakeRequest` here)
3. In OnWelcome func, we will have that cookie generated _for this connection_ and authid, so we save cookie value in database _for this authid_
4. Next time client requests WS, we read cookie from Request and if it's found in database for any authid, we log that user in.

What's your opinion on this flow? I'm in the middle of implementing this on the app I'm currently working on, but looks like it's impossible without some additions to nexus.

**Comment by gammazero** [comment]
For cookie auth, this flow is what I was thinking, and it can be done without breaking backwards compatibility.  I am happy to make changes to nexus auth implementation to make it more useful.

I am not sure that we want to expose the handshake request to KeyStore, since the cookie auth bypasses using KeyStore.  In other words, KeyStore is what provides access to keys the router needs for authentication; Router implementers provide the implementation needed to fetch keys.  With cookie auth, the router determines that the client is already authenticated by the cookie, so does not need to use KeyStore to get keys.  I want to keep KeyStore as simple as possible so the implementer only needs to care about how to provide keys.

Maybe I am not understanding all that you want to do with `OnWelcome()`.  To me, I think managing the cookie DB is not part of KeyStore.

I will start implementation, unless you already have some example code we can start working from.

**Comment by azamat-sharapov** [comment]
> I will start implementation, unless you already have some example code we can start working from.

No, I haven't started anything related to it, wanted to discuss first. But I'll leave it to you, since I'm not pro with golang yet :)

**Comment by gammazero** [comment]
Before I start, what do you see as the responsibility of `OnWelcome`?  So far is seems that it should store cookie in DB for authid, and update expiration time whenever cookie used.  Stored data will include handshakeRequest and sessionDetails. What else?
- Does `OnWelcome` need to be an interface that an implementation can be provided for, or should `OnWelcome` be a private function in the router?
- How long should unused cookies be stored?  Configurable? Default expiration?
- Should cookie DB entry expiration be updated each time it is used, or should it expire after some time regardless of use to require re-authentication?

As far as exposing handshake to KeyStore, would that be for using information, other then just the authid, for retrieving keys?  If so, would it be sufficient to supply Hello.Details as an additional parameter here: https://github.com/gammazero/nexus/blob/master/router/auth/crauth.go#L38 ?

**Comment by azamat-sharapov** [comment]
> Does OnWelcome need to be an interface that an implementation can be provided for, or should OnWelcome be a private function in the router?

It should interface, not private, because one could do more on user land, like updating more records in database, etc.

> How long should unused cookies be stored? Configurable? Default expiration?

Configurable. I think it should default to `0`, making it "required option".

> Should cookie DB entry expiration be updated each time it is used, or should it expire after some time regardless of use to require re-authentication?

Would like that to be configurable too.

> As far as exposing handshake to KeyStore, would that be for using information, other then just the authid, for retrieving keys? If so, would it be sufficient to supply Hello.Details as an additional parameter here...

Yes!

**Comment by gammazero** [comment]
> Next time client requests WS, we read cookie from Request and if it's found in database for any authid, we log that user in.

I think that if client presents cookie that is found in database, then authid requested by client must match authid saved with cookie.  If we do not do this, and login the client with the authid of the cookie, this may cause unexpected results when the client gets logged in as a different authid than the one that was in the HELLO.

**Comment by azamat-sharapov** [comment]
> authid saved with cookie

I also thought about this, but while creating a cookie, we yet don't have authid. User will provide authid over websocket connection, while authenticating using CR/ticket.

**Comment by azamat-sharapov** [comment]
Also, I'm using `gorilla/session` for this scenario, it encrypts cookies.

**Comment by gammazero** [comment]
Tracking cookies can be enabled to identify returning websocket clients.  When enabled in the router, a random cookie is sent in the websocket upgrade response.  The client can return the cookie in subsequent websocket requests.  This may be used by authenticators to determine that a client is already authenticated, and bypass CR or ticked auth.  The tracking cookie can be used for whatever purpose the router wants to identify a returning websocket client.

Information from the websocket upgrade request is captured in HELLO/session details, Details.transport.auth.request.  This exposes it to auth/authz logic.

Currently Details.transport.auth is not included with session meta information, so at to avoid giving away authentication-related information.

This new functionality is in the [cookieauth](https://github.com/gammazero/nexus/tree/cookieauth) branch.  If this seems like a reasonable implementation I will PR.

**Comment by gammazero** [comment]
@crabicode, @azamat-sharapov I think #88 has what you are looking for.  See comment on PR.

**Comment by azamat-sharapov** [comment]
@gammazero Thanks! I've looked through and looks like it's what I'm looking for. However, for my case, I had to create custom Authenticator, since CR or ticket didn't work (I created BcryptAuthenticator, because existing auth methods don't work with stored password hashes). Now I need to integrate cookie auth into it.

**Comment by gammazero** [comment]
OK, this will give you all the ability to integrate cookie auth (as well as use other request info like headers) in your authenticator.  For the tracking cookie (that can be used as auth cookie) it is generated for you, since the response to the upgrade request must be sent back before your auth functionality is ever called.  So, you store the nextCookie once the client is authenticated.

The KeyStore (or BypassKeyStore) should allow the existing implementations to work with stored passwords - you just need to implement the storage/retrieval part.  If there are features to add or change so that it would work for you, I would like to understand better what you need.

**Comment by azamat-sharapov** [comment]
@gammazero I successfully integrated cookie auth to my custom authenticator (it's very similar to ticket authenticator), with the help of your tests. Looking forward to see this on master branch soon. Thank you!

**Comment by gammazero** [comment]
That's great news.  I will see if @crabicode has anything to say in the next day, give this a final review, and then merge!

**Comment by gammazero** [comment]
Resolved by PR #88
