### ISSUE TITLE
ConnectLocal with no auth

### ISSUE THREAD

**Issue by azamat-sharapov** [gammazero/nexus#78]
My setup is:

NexusRouter <-> NexusClient (using ConnectLocal) <-> FrontendClient (on browser, via [wampy.js](https://github.com/KSDaemon/wampy.js))

I would like to implement CR auth between NexusRouter and FrontendClient, but I don't need any auth between NexusRouter and NexusClient. 

One workaround would be to use ticket auth between NexusRouter and NexusClient, but that would make ticket auth available for FrontendClient too, which I don't want. I read through docs and source, but couldn't find any other option. Authentication to connect to local router doesn't make sense to me, since it's within the application, not separate. Is it possible to make no-auth connection between NexusRouter and NexusClient? 

Thanks

**Comment by gammazero** [comment]
I think you are right that local connection should not require auth, since it is within the same process.  I will make a change so that local clients do not require auth.  I should be able to complete this weekend.

**Comment by gammazero** [comment]
Will merge #79 tonight.  Local clients will no longer require auth.

**Comment by gammazero** [comment]
Please confirm this fixes this issue and close.

**Comment by azamat-sharapov** [comment]
It works, thank you!
