### ISSUE TITLE
Setting http headers on upgrade

### ISSUE THREAD

**Issue by azamat-sharapov** [gammazero/nexus#83]
I would like to set some cookies on client-side (browser) via upgrader, but I see I [can't add headers on upgrader](https://github.com/gammazero/nexus/blob/master/router/websocketserver.go#L135).

Should I send PR for this?

**Comment by gammazero** [comment]
PR or discussion.  Since this is useful to multiple parties, see #67, let's design a good interface for doing this.

**Comment by azamat-sharapov** [comment]
I've opened PR #86. If you think this is not right way, please let me know :)

**Comment by gammazero** [comment]
PR #86 merged.
