### ISSUE TITLE
Thread saftey

### ISSUE THREAD

**Issue by koliyo** [gammazero/nexus#84]
Is the API thread safe? I'm getting really strange bugs and think this may be due to data races. Eg
```
WARNING: DATA RACE
Read at 0x00c4200165b0 by goroutine 21:
  github.com/gammazero/nexus/client.(*Client).CallProgress()
      /Users/nils/Work/go/src/github.com/gammazero/nexus/wamp/idgen.go:41 +0xdd
  github.com/gammazero/nexus/client.(*Client).Call()
...
Previous write at 0x00c4200165b0 by goroutine 20:
  github.com/gammazero/nexus/client.(*Client).CallProgress()
      /Users/nils/Work/go/src/github.com/gammazero/nexus/wamp/idgen.go:41 +0xf9
  github.com/gammazero/nexus/client.(*Client).Call()
```

Do I need to serialize these calls?

**Comment by ajgillis** [comment]
You should not need to serialize the calls.  It looks like the issue is in the use of the ID generator.  I will fix this now.

**Comment by gammazero** [comment]
You should not need to serialize the calls. It looks like the issue is in the use of the ID generator. I will fix this now.

**Comment by koliyo** [comment]
Great! Please also add some unittesting for the client which does large amounts of concurrent RPC calls and topic publishing from multiple coroutines. That would help guarantee the functionality.

You probably need to bypass the local transport for this, and use WebSocket transport.
