### ISSUE TITLE
Get session ID in InvocationHandler

### ISSUE THREAD

**Issue by azamat-sharapov** [gammazero/nexus#91]
Is it possible to somehow pass session ID (that is created [here](https://github.com/gammazero/nexus/blob/e8d9fe460c6512645f238ed8a91c3086381f45c3/router/router.go#L250)) to InvocationHandler?

My goal is to store some data in memory for each session (`data map[wamp.ID]SomeData`) so that I can then access that data in InvocationHandler, like following:

```
func someRpcHandler(ctx context.Context, args wamp.List, kwargs, details wamp.Dict) *client.InvokeResult {
  dataFromMemory := data[sessionIdHere]
}
```

**Comment by ajgillis** [comment]
Since you already have `*client`, that you used to register the invocation handler, you can call `callee.ID()`, where your client is `callee`.
https://github.com/gammazero/nexus/blob/master/client/client.go#L207

Usually the handlers are defined as closures, which is the reason that the client is not passed into the function as an argument.   Example follows:
```
// Define RPC handler that computes sum of integer args.
someRpcHandler := func(ctx context.Context, args wamp.List, kwargs, details wamp.Dict) *client.InvokeResult {
	var sum int64
	for i := range args {
		n, ok := wamp.AsInt64(args[i])
		if ok {
			sum += n
		}
	}
	fmt.Println("Client session", calllee.ID(), "calculated sum", sum)
	return &client.InvokeResult{Args: wamp.List{sum}}
}

// Register procedure "sum"
procName := "sum"
if err = callee.Register(procName, someRpcHandler, nil); err != nil {
	t.Fatal("Failed to register procedure:", err)
}
```

**Comment by azamat-sharapov** [comment]
The problem is that I need session ID, not client ID. Clients come from browser (websocket peer) and each time they authenticate, session ID changes, but client ID stays the same (local peer).

**Comment by ajgillis** [comment]
OK,  I see. You want your `callee` to get the ID of the `caller` session.  That way that works in WAMP is for the _Callee_ to request `disclose_caller`, and for the _Caller_ to request `disclose_me`.
https://github.com/gammazero/nexus/blob/master/client/client.go#L431-L432
https://github.com/gammazero/nexus/blob/master/client/client.go#L588-L589

The _Callee_ needs to set `options["disclose_caller"] = true` in the options when it calls `Register`.  The _Caller_ needs to set `options["disclose_me"] = true` when it calls `Call`.

**Comment by azamat-sharapov** [comment]
`disclose_caller` option is what I need, thanks! Just one last question: can I somehow catch "session lost", so that I could provide callback to keep data store clean by removing invalid sessions?

**Comment by ajgillis** [comment]
I believe what you are looking for is the WAMP feature called "Testament":
```
When a WAMP client disconnects, or the WAMP session is destroyed, it may want to notify other subscribers or publish some fixed data. Since a client may disconnect uncleanly, this can't be done reliably by them. A Testament, however, set on the server, can be reliably sent by the Broker once either the WAMP session has detached or the client connection has been lost, and allows this functionality. It can be triggered when a Session is either detached (the client has disconnected from it, or frozen it, in the case of Session Resumption) or destroyed (when the WAMP session no longer exists on the server).
```

http://wamp-proto.org/static/rfc/draft-oberstet-hybi-crossbar-wamp.html#testament

If this is what you need, then I will implement this.

**Comment by azamat-sharapov** [comment]
"Testament" is similar, but probably won't work for my case.. What I mainly need is to get invalid/obsolete session IDs and remove them from local variable. But looking at wamp docs, I see "session meta events", which include `wamp.session.on_leave` and `wamp.session.list`. Is it possible, that *only* local nexus client subscribes to them? and if other peers (websocket peers, coming from browser) leave session, local client would get notified and run clean-up code.

**Comment by ajgillis** [comment]
Seems like that would work.  Have your local clients subscribe to the `wamp.session.on_leave` meta event, and use the `wamp.session.list` meta procedure to get the initial list of sessions.

If you need to enforce that _only_ local clients can subscribe, then use an authorizer to excluded non-local clients.  Local clients do not require authentication, and are always assigned:
```
"authrole": "trusted"
"authmethod": "local"
```

**Comment by azamat-sharapov** [comment]
Appreciate your help, meta event and procedures worked for my case.
