### ISSUE TITLE
HTTP RESTful bridge to WAMP

### ISSUE THREAD

**Issue by GFariasR** [gammazero/nexus#92]
I was not sure where to post a question, so I decided to open an issue instead.

I am looking for a WAMP router that can take a HTTP POST request (with the payload needed to identify an RPC URI) and transform that into an existing WAMP.

My understanding is this is not part of the WAMP protocol. 

My question is: does NEXUS support this API? 

Thanks,

**Comment by gammazero** [comment]
The short answer is no, nexus does not support that.  However, that can be implemented in the HTTP POST handler that talks to nexus.

It sounds like you want something that sets up the websocket, establishes a WAMP session, and then invokes RPC functionality all in one step, using data provided in POST.  

Your code that handles the POST would need to perform those steps as part of handling the POST:
1. Websocket handshake - send upgrade request to nexus, get response
2. Establish WAMP session - client sends HELLO, router response WELCOME
3. Invoke RPC functionality
4. Return HTTP response to POST

So it can be implemented, but is not something that nexus already provides.  Maybe this could be a useful utility that can be used to adapt web services to use WAMP RPC.

**Comment by GFariasR** [comment]
Thanks for your response. I will investigate the path you proposed.
