### ISSUE TITLE
Wrong deserialization when using msgpack

### ISSUE THREAD

**Issue by martin31821** [gammazero/nexus#97]
Using msgpack to deserialize dictionaries gives objects of type `map[interface{}]interface{}` whereas json (and possibly cbor too, I haven't tested yet) yield `map[string]interface{}`.

This leads to the following problem:
When I have a client `A` connected to the router `R` using msgpack and a client `B` connected to `R` using json (e.g. a browser) there is the possibility that `R` decodes some dictionaries in a `map[interface{}]interface{}` and is unable to reencode this object into json.
This eventually leads to an exception and ultimately to closed connections.

The fix is to add: `mph.MapType = reflect.TypeOf(map[string]interface{}(nil))` to `msgpackserializer.go` in line 21 and 32. (for both code parts).

I can prepare a PR for this.

**Comment by ajgillis** [comment]
Yes please PR. Then you get credit for fix.

**Comment by gammazero** [comment]
Yes please PR. I would be happy to add that, but it would be good if you get credit for fix.  I need to make sure there is a unit test that covers that case.
